/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import archivos.Archivo;
import java.awt.Color;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class FormularioContacto extends javax.swing.JFrame {

    final int INITIAL_WEIGHT = 450; // Ancho inicial de la ventana
    final int INITIAL_HEIGHT = 400; // Alto inicial de la ventana
    final String TITLE = "Simulador de CallCenter"; // Título de la ventana
    final String SEARCH = "Buscar"; // Texto de búsqueda por defecto

    private Archivo archivo; // Manejo de archivos para guardar y cargar contactos
    private Contacto contacto; // Objeto Contacto que se manipulará
    private Libreta libreta; // Lista de contactos
    private String[] stringContactos; // Arreglo para almacenar los contactos como cadenas
    private String cedula; // Cédula del contacto
    private Queue<Contacto> pendientes = new LinkedList<>(); // Cola para manejar contactos
    private Stack<Contacto> atentidos;//Pila de contactos atendidos
    private boolean estadoB = false; // Estado del botón
    private boolean estadoPanel = true; // Estado del panel
    private int selTipo = 0; // Tipo de selección (mostrar cédulas o todo)
    // Clases encargas de manipular las listas
    private DefaultListModel<String> lmPendientes = new DefaultListModel<>();
    private DefaultListModel<String> lmAtendidos = new DefaultListModel<>();

    //Constructor de la GUI
    public FormularioContacto() {
        initComponents();// inicializa componentes 
        archivo = new Archivo();
        libreta = new Libreta();

        setLocationRelativeTo(null);
        super.setSize(INITIAL_WEIGHT, INITIAL_HEIGHT);
        super.setTitle(TITLE);
    }

    public void limpiar() {
        textCedula.setText("");
        textNombre.setText("");
        textApellidos.setText("");
        textFechaNac.setText("");
        textTelefono.setText("");
        textCorreo.setText("");
    }

    public void listar() {
        listar(this.selTipo);
    }

    /**
     * Lista los contactos según el tipo especificado.
     *
     * @param tipo Tipo de listado (0: mostrar cédulas, 1: mostrar todos).
     */
    public void listar(int tipo) {
        String search = searchText.getText();
        if (!search.equals(SEARCH)) {
            this.libreta.buscarArchivos(searchText.getText()); // Busca contactos que coincidan con el texto
        }

        switch (tipo) {
            case 0: {
                this.stringContactos = libreta.listarCedulas(); // Lista solo cédulas
                listaContactos.setListData(this.stringContactos);
            }
            break;
            case 1: {
                this.stringContactos = libreta.listarLibreta(); // Lista todos los contactos
                listaContactos.setListData(this.stringContactos);
            }
            break;
        }
    }

    /**
     * Llena los campos del formulario con la información del contacto
     * seleccionado.
     */
    public void llenarCampos() {
        textCedula.setText(this.contacto.getCedula());
        textNombre.setText(this.contacto.getNombre());
        textApellidos.setText(this.contacto.getApellidos());
        textFechaNac.setText(this.contacto.getfNacimiento());
        textTelefono.setText(this.contacto.getTelefono());
        textCorreo.setText(this.contacto.getCorreo());
        provinciasComboBox.setSelectedItem(this.contacto.getProvincia());
    }

    /**
     * Método generado automáticamente para inicializar los componentes del
     * formulario.
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gMostrar = new javax.swing.ButtonGroup();
        panelListaCont = new javax.swing.JPanel();
        panelContacto = new javax.swing.JPanel();
        bGuardar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        textFechaNac = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bLimpiar = new javax.swing.JButton();
        textCorreo = new javax.swing.JTextField();
        bBusqueA = new javax.swing.JToggleButton();
        textCedula = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        provinciasComboBox = new javax.swing.JComboBox<>();
        panelControl = new javax.swing.JPanel();
        bAbrir = new javax.swing.JButton();
        bImportar = new javax.swing.JButton();
        panelMostrar = new javax.swing.JPanel();
        mostrarCed = new javax.swing.JRadioButton();
        mostrarTodo = new javax.swing.JRadioButton();
        searchText = new javax.swing.JTextField();
        bLimpiarBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaContactos = new javax.swing.JList();
        panelLlamadas = new javax.swing.JPanel();
        btnContactar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPendientes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAtendidos = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAteTelefono = new javax.swing.JTextField();
        txtAteNombre = new javax.swing.JTextField();
        lblTiempo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(412, 634));

        panelContacto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelContacto.setPreferredSize(new java.awt.Dimension(450, 312));

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/add.png"))); // NOI18N
        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/search.png"))); // NOI18N
        bBuscar.setToolTipText("Busqueda por cedula");
        bBuscar.setAlignmentY(0.0F);
        bBuscar.setMargin(new java.awt.Insets(1, 5, 1, 5));
        bBuscar.setPreferredSize(new java.awt.Dimension(26, 23));
        bBuscar.setRequestFocusEnabled(false);
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/remove.png"))); // NOI18N
        bEliminar.setToolTipText("Eliminar");
        bEliminar.setAlignmentY(0.0F);
        bEliminar.setMargin(new java.awt.Insets(1, 5, 1, 5));
        bEliminar.setPreferredSize(new java.awt.Dimension(26, 23));
        bEliminar.setRequestFocusEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        jLabel4.setText("Fecha Nacimiento");

        jLabel3.setText("Apellidos");

        jLabel5.setText("Provincia");

        jLabel6.setText("Teléfono");

        jLabel7.setText("Correo");

        bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/page.png"))); // NOI18N
        bLimpiar.setText("Nuevo");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        bBusqueA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/database_search.png"))); // NOI18N
        bBusqueA.setText("Ver detalles");
        bBusqueA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBusqueAActionPerformed(evt);
            }
        });

        textCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textCedulaKeyReleased(evt);
            }
        });

        provinciasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limón" }));

        javax.swing.GroupLayout panelContactoLayout = new javax.swing.GroupLayout(panelContacto);
        panelContacto.setLayout(panelContactoLayout);
        panelContactoLayout.setHorizontalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContactoLayout.createSequentialGroup()
                        .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelContactoLayout.createSequentialGroup()
                                .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContactoLayout.createSequentialGroup()
                                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textCorreo)
                                    .addComponent(textTelefono)
                                    .addComponent(textApellidos)
                                    .addComponent(textFechaNac)
                                    .addComponent(textNombre)
                                    .addComponent(textCedula)
                                    .addComponent(provinciasComboBox, 0, 259, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bBusqueA)
                        .addGap(18, 18, 18)
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bGuardar)
                        .addGap(146, 146, 146))))
        );
        panelContactoLayout.setVerticalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(provinciasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardar)
                    .addComponent(bLimpiar)
                    .addComponent(bBusqueA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/folder_edit.png"))); // NOI18N
        bAbrir.setText("Abrir");
        bAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirActionPerformed(evt);
            }
        });

        bImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/page_down.png"))); // NOI18N
        bImportar.setText("Importar");
        bImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImportarActionPerformed(evt);
            }
        });

        panelMostrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Mostar:"));

        gMostrar.add(mostrarCed);
        mostrarCed.setSelected(true);
        mostrarCed.setText("Por cedulas");
        mostrarCed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrarCedItemStateChanged(evt);
            }
        });

        gMostrar.add(mostrarTodo);
        mostrarTodo.setText("Todo");
        mostrarTodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mostrarTodoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelMostrarLayout = new javax.swing.GroupLayout(panelMostrar);
        panelMostrar.setLayout(panelMostrarLayout);
        panelMostrarLayout.setHorizontalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addComponent(mostrarCed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(mostrarTodo))
        );
        panelMostrarLayout.setVerticalGroup(
            panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarLayout.createSequentialGroup()
                .addGroup(panelMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarCed)
                    .addComponent(mostrarTodo))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        searchText.setForeground(java.awt.Color.gray);
        searchText.setText(SEARCH);
        searchText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFocusLost(evt);
            }
        });
        searchText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTextKeyTyped(evt);
            }
        });

        bLimpiarBuscar.setText("Limpiar");
        bLimpiarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarBuscarActionPerformed(evt);
            }
        });

        listaContactos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaContactosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaContactos);

        javax.swing.GroupLayout panelControlLayout = new javax.swing.GroupLayout(panelControl);
        panelControl.setLayout(panelControlLayout);
        panelControlLayout.setHorizontalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(bAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bImportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(panelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addComponent(searchText)
                        .addGap(13, 13, 13)
                        .addComponent(bLimpiarBuscar)))
                .addContainerGap())
        );
        panelControlLayout.setVerticalGroup(
            panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControlLayout.createSequentialGroup()
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelControlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bAbrir)
                            .addComponent(bImportar)))
                    .addComponent(panelMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLimpiarBuscar)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btnContactar.setText("Contactar");
        btnContactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactarActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setEnabled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListPendientes);

        jScrollPane3.setViewportView(jListAtendidos);

        jLabel8.setText("Pendientes:");

        jLabel9.setText("Atendidos:");

        txtAteTelefono.setEditable(false);
        txtAteTelefono.setText("Telefono");

        txtAteNombre.setEditable(false);
        txtAteNombre.setText("Nombre");
        txtAteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAteNombreActionPerformed(evt);
            }
        });

        lblTiempo.setFont(new java.awt.Font("Fira Code", 1, 18)); // NOI18N
        lblTiempo.setText("0:00:00");

        jButton3.setText("Llamar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Colgar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLlamadasLayout = new javax.swing.GroupLayout(panelLlamadas);
        panelLlamadas.setLayout(panelLlamadasLayout);
        panelLlamadasLayout.setHorizontalGroup(
            panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLlamadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLlamadasLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(panelLlamadasLayout.createSequentialGroup()
                        .addComponent(txtAteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLlamadasLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblTiempo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLlamadasLayout.createSequentialGroup()
                        .addComponent(btnContactar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)))
                .addContainerGap())
        );
        panelLlamadasLayout.setVerticalGroup(
            panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLlamadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnContactar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLlamadasLayout.createSequentialGroup()
                            .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(lblTiempo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelLlamadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton4)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelListaContLayout = new javax.swing.GroupLayout(panelListaCont);
        panelListaCont.setLayout(panelListaContLayout);
        panelListaContLayout.setHorizontalGroup(
            panelListaContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaContLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelListaContLayout.createSequentialGroup()
                        .addComponent(panelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelLlamadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelListaContLayout.setVerticalGroup(
            panelListaContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaContLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelListaContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(panelControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelLlamadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListaCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelListaCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        //Cedula// funcion de textCedula actuliza cedula al digitar
        String provincia = String.valueOf(provinciasComboBox.getSelectedItem());
        contacto = new Contacto(cedula,
                textNombre.getText(),
                textApellidos.getText(),
                textFechaNac.getText(),
                provincia,
                textTelefono.getText(),
                textCorreo.getText());
        libreta.actualizarContacto(contacto);

        //Listar contactos en Jlist
        this.cedula = contacto.getCedula();

        bLimpiarActionPerformed(evt);
        listar();
        listaContactos.setSelectedValue(cedula, true);
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        if (libreta.eliminarContacto(textCedula.getText())) {
            bLimpiarActionPerformed(evt);
            listar();
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        this.cedula = textCedula.getText();
        if (!(cedula.equals(""))) {
            archivo = new Archivo(cedula);
            this.contacto = archivo.consulta(cedula);

            if (archivo.existe(textCedula.getText())) {
                llenarCampos();
            }
        } else {

            JOptionPane.showMessageDialog(null, "Digite una cedula para buscar la informacion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        limpiar();
        super.setTitle(TITLE);
        listaContactos.setSelectedValue(null, true);
    }//GEN-LAST:event_bLimpiarActionPerformed
    private void listaContactosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaContactosValueChanged
        if (!(listaContactos.getSelectedIndex() == -1)) {

            archivo = new Archivo();
            if (mostrarCed.isSelected()) {

                super.setTitle(TITLE + " - " + cedula);

                this.cedula = (listaContactos.getSelectedValue().toString());
                //Llenar campos
                this.contacto = archivo.consulta(cedula);
                llenarCampos();
            } else {

                this.cedula = (listaContactos.getSelectedValue().toString());
                StringTokenizer tokens = new StringTokenizer(cedula);
                this.cedula = tokens.nextToken(",");

                //Llenar campos
                this.contacto = archivo.consulta(cedula);
                llenarCampos();
            }

        } else {
            limpiar();
        }

    }//GEN-LAST:event_listaContactosValueChanged

    private void bBusqueAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBusqueAActionPerformed
        this.estadoB = !estadoB;
        if (estadoB) {
            int w = INITIAL_WEIGHT + panelControl.getWidth() + 5;
            int h = INITIAL_HEIGHT + panelLlamadas.getHeight() + 5;
            super.setSize(w, h);

            //Llenar lista de contactos//
            //Las siguientes validaciones evitan que se limpie la infomacion en pantalla al esconder la lista
            if (stringContactos != null) {
                if (stringContactos[0].equals("")) {
                    listar();
                }
            } else {
                listar();
            }
        } else {
            super.setSize(INITIAL_WEIGHT, INITIAL_HEIGHT);
        }
    }//GEN-LAST:event_bBusqueAActionPerformed

    private void textCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textCedulaKeyReleased
        this.cedula = textCedula.getText();
    }//GEN-LAST:event_textCedulaKeyReleased

    private void mostrarCedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrarCedItemStateChanged
        this.selTipo = 0;
        listar();
    }//GEN-LAST:event_mostrarCedItemStateChanged

    private void mostrarTodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mostrarTodoItemStateChanged
        this.libreta = new Libreta();
        this.selTipo = 1;
        listar();
    }//GEN-LAST:event_mostrarTodoItemStateChanged

    private void bImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImportarActionPerformed
        this.contacto = archivo.consultaImportar();
        bLimpiarActionPerformed(evt);
        llenarCampos();
        this.cedula = textCedula.getText();
    }//GEN-LAST:event_bImportarActionPerformed

    private void bAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirActionPerformed
        try {
            archivo.abrir(cedula);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_bAbrirActionPerformed

    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
        if (searchText.getText().equals(SEARCH)) {
            searchText.setText("");
            searchText.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        if (searchText.getText().isEmpty()) {
            searchText.setForeground(Color.GRAY);
            searchText.setText(SEARCH);
        }
    }//GEN-LAST:event_searchTextFocusLost

    private void bLimpiarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarBuscarActionPerformed
        searchText.setText(SEARCH);
        searchText.setForeground(Color.GRAY);
        listar();
    }//GEN-LAST:event_bLimpiarBuscarActionPerformed

    private void searchTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyTyped
        listar();
    }//GEN-LAST:event_searchTextKeyTyped

    private void searchTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextKeyReleased
        listar();
    }//GEN-LAST:event_searchTextKeyReleased

    private void actualizarListas() {
        lmPendientes.clear();
        for (Contacto c : pendientes) {
            lmPendientes.addElement(c.getNombreCompleto());
        }
        jListPendientes.setModel(lmPendientes);
        btnContactar.setEnabled(pendientes.isEmpty());
        btnSiguiente.setEnabled(!pendientes.isEmpty());
    }
    private void btnContactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactarActionPerformed
        lmPendientes = new DefaultListModel<>();

        for (Contacto c : libreta.getLibreta()) {
            pendientes.add(c);
            lmPendientes.addElement(c.getNombreCompleto());
        }
        jListPendientes.setModel(lmPendientes);
        btnContactar.setEnabled(false);
        btnSiguiente.setEnabled(true);

        txtAteNombre.setText("Telefono");
        txtAteTelefono.setText("Nombre Completo");
    }//GEN-LAST:event_btnContactarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        Contacto siguiente = pendientes.poll();
        txtAteNombre.setText(siguiente.getNombreCompleto());
        txtAteTelefono.setText(siguiente.getTelefono());
        actualizarListas();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtAteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAteNombreActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioContacto.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormularioContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrir;
    private javax.swing.JButton bBuscar;
    private javax.swing.JToggleButton bBusqueA;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bImportar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bLimpiarBuscar;
    private javax.swing.JButton btnContactar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup gMostrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListAtendidos;
    private javax.swing.JList<String> jListPendientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JList listaContactos;
    private javax.swing.JRadioButton mostrarCed;
    private javax.swing.JRadioButton mostrarTodo;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelListaCont;
    private javax.swing.JPanel panelLlamadas;
    private javax.swing.JPanel panelMostrar;
    private javax.swing.JComboBox<String> provinciasComboBox;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textFechaNac;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField txtAteNombre;
    private javax.swing.JTextField txtAteTelefono;
    // End of variables declaration//GEN-END:variables
}
